### ISSUE TITLE
偶数页的内容没有居中,偏右

### ISSUE THREAD

**Issue by guanyingc** [chungkwong/sysu_thesis#1]
非常感谢师兄的工作,我现在打算用师兄的模板做毕业论文,也趁这个机会好好学习一下LaTex.

我现在可以编译过去,得到的pdf已经非常好了,不过我发现偶数页的内容会向右偏移,没有居中,奇数页是正常的.不知道师兄自己编译的会不会?

希望师兄可以给我点指导,万分感谢了!

**Comment by chungkwong** [comment]
如果双面打印，区分左右页合理的，实际上是LaTeX的book文类的默认行为。如果只想改为居中，应该只用把sysuthesis.cls中
`\RequirePackage[margin=1in,outer=1.5in]{geometry}`
改为
`\RequirePackage[margin=1in]{geometry}`。
如果想单面打印，还应把ctexbook均替换为ctexrep，另外还可能有几处小改动，如\bibname改为\refname。

**Comment by guanyingc** [comment]
非常感谢师兄的回答,真的好感动.
我昨晚问的问题,然后我早上发现了这时book类的默认行为,所以赶紧把问题给关闭了,没想到师兄还会耐性给我指出来.

我看了一下,和学校给的模板已经很接近了,可能还需要修改一些地方,比如
- 摘要上方的信息
- 正文的页眉
  我会尽力自己去查找方法解决的.我先不麻烦师兄.希望到时遇到一些实在没法解决的问题时,师兄可以抽空帮忙一下!

打扰师兄啦!
[template.pdf](https://github.com/chungkwong/sysu_thesis/files/146780/template.pdf)
